name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    env:
      JAVA_TOOL_OPTIONS: "-Xmx8g"
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx8g -Dkotlin.daemon.jvm.options=-Xmx2g"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          cache: true

      - name: Clean Gradle Cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon

      # Create keystore
      
            - name: Decode Keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          mkdir -p android/cert

          echo "$ANDROID_KEYSTORE" | base64 --decode > android/cert/iskcon-keystore.jks

          echo "Secret length: ${#ANDROID_KEYSTORE}"
          ls -la android
          ls -la android/cert

          if [ -f android/cert/iskcon-keystore.jks ]; then
            echo "Keystore created successfully"
            wc -c android/cert/iskcon-keystore.jks
          else
            echo "Keystore NOT created"
            exit 1
          fi

      - name: Create key.properties
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=cert/iskcon-keystore.jks
          EOF

          echo "===== key.properties ====="
          cat android/key.properties

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Verify Signing Files
        run: |
          pwd
          ls -la android
          ls -la android/cert
          cat android/key.properties

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/app/outputs/flutter-apk/app-release.apk